### ISSUE TITLE
Manager::Worker::HireFire::JobLatency not supported

### ISSUE THREAD

**Issue by KevinCarterDev** [carwow/terraform-provider-hirefire#21]
`Manager::Worker::HireFire::JobLatency` isn't listed as a valid type for `hirefire_manager`. This is due to the type not previously being listed in the API docs. I've spoken with HireFire and they've updated the docs and the `Manager::Worker::HireFire::JobLatency` type is now listed at https://docs.hirefire.io/api/manager/create/

Can this type and it's parameters be added to the `hirefire_manager` resource?

**Comment by PChambino** [comment]
Hi @KevinCarterDev 

Thanks for letting us know. Version v0.5.0 now supports the `Manager::Worker::HireFire::JobLatency` manager and its parameters. Let me know if something else is missing.
